version: '3'
services:
  www:
    container_name: 'simplerisk-www'
    build:
      context: ./simplerisk/
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - PRIVATE_KEY
      - CERTIFICATE
    volumes:
      - ./data/logs/www:/var/log/apache2
    ports:
      - "80"
      - "443"
    depends_on:
      - database
    links:
      - database
  database:
    container_name: 'simplerisk-db'
    build:
      context: ./database/
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ./data/database:/var/lib/mysql
      - ./data/logs/database:/var/log/mysql
    ports:
      - "3306"
